backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "assets/images"

collections:
  - name: "produits"
    label: "Produits"
    files:
      - name: "catalogue"
        label: "Catalogue Complet"
        file: "data/produits.json"
        fields:
          - name: "items"
            label: "Liste des Produits"
            widget: "list"
            fields:
              - {label: "ID Unique (Ne pas toucher)", name: "id", widget: "uuid"}
              - {label: "Nom du produit", name: "nom", widget: "string"}
              - {label: "Prix (FCFA)", name: "prix", widget: "number", value_type: "int"}
              - {label: "Stock", name: "stock", widget: "number", default: 1}
              - {label: "Catégorie", name: "categorie", widget: "select", options: ["Sacs", "Chaussures", "Robes", "Accessoires", "Jeans"]}
              - {label: "Image Principale", name: "image", widget: "image"}
              # --- NOUVEAU BLOC POUR LA GALERIE ---
              - label: "Galerie Photos (Optionnel)"
                name: "images"
                widget: "list"
                field: {label: "Photo supplémentaire", name: "img", widget: "image"}
              # ------------------------------------
              - {label: "Description", name: "description", widget: "text"}
              - {label: "En Story ?", name: "in_story", widget: "boolean", default: false, required: false}
