backend:
  name: github
  repo: urbain7/Sandy-shop
  branch: main

media_folder: "images/uploads" # Où vont les nouvelles images
public_folder: "images/uploads"

collections:
  - name: "produits"
    label: "Produits"
    files:
      - name: "catalogue"
        label: "Catalogue Général"
        file: "data/produits.json" # Le fichier qu'on modifie
        fields:
          - name: "items"
            label: "Liste des produits"
            widget: "list"
            fields:
              - {label: "ID Unique", name: "id", widget: "string"}
              - {label: "Nom du produit", name: "nom", widget: "string"}
              - {label: "Prix (FCFA)", name: "prix", widget: "number"}
              - {label: "Stock", name: "stock", widget: "number", default: 1}
              - {label: "Catégorie", name: "categorie", widget: "select", options: ["Sacs", "Chaussures", "Robes", "Accessoires", "Jeans"]}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Afficher en Story ?", name: "in_story", widget: "boolean", default: false}
